### ISSUE TITLE
Rum no longer supports `cursored` and `cursored-watch`. How does the getting started with rum change?

### ISSUE THREAD

**Issue by robert-stuttaford** [bilus/reforms#14]
See https://github.com/tonsky/rum#0100.

Can we perhaps use `rum/cursor` and/or `rum/reactive` + `rum/react`?

**Comment by aspasia** [comment]
I will upgrade rum and create working examples for the run binding asap

**Comment by aspasia** [comment]
Related issue https://github.com/aspasia/rum-reforms/issues/1
