### ISSUE TITLE
REQ: Make label optional

### ISSUE THREAD

**Issue by ryanbaldwin** [bilus/reforms#2]
Great little library you've started here. Nice work!

Feature request: make labels optional.

**Comment by bilus** [comment]
Good idea, I'll see what I can do. Thanks!

**Comment by bilus** [comment]
I have good news for you. Check out the master branch (version 0.4.0-SNAPSHOT). It lets you skip the label argument and put the (optional) placeholder into options like that:

```clojure
; With label:
(f/text "Your name" data [:name] :placeholder "Type your name here")
; Without label:
(f/text data [:name] :placeholder "Type your name here")
```

placeholder as a positional argument is still supported but generates a deprecation warning:

```clojure
; Don't do that anymore
(f/text "Your name" "Type your name here" data [:name])
```
This isn't production-ready yet (plus there are more features to be added until 0.4.0 is out) so if you notice any bugs, do let me know.

**Comment by ryanbaldwin** [comment]
Groovy man. Thanks!



- ryan.
