### ISSUE TITLE
Table with row selection: error when initial value of selected is 'nil'

### ISSUE THREAD

**Issue by Frozenlock** [bilus/reforms#5]
To reproduce: 

- Go to the [demo page](http://bilus.github.io/reforms/examples/reagent/controls/index.html).

- Before doing anything else, click on the `hero name` checkbox.

Because the current value at path `:selected` is nil, it will produce an error.

**Comment by bilus** [comment]
Great catch, that's because when extracting the code from the main code base, I changed the default behaviour where nil selection means 'all is selected'. 

I'm pushing out 0.4.3 right now -- it should fix the issue. Thanks!

**Comment by Frozenlock** [comment]
Thanks for the quick fix!
